name: Data Theorem Mobile Secure
description: |
  Data Theorem's Mobile Secure will scan each pre-production release automatically (up to 7000 releases/day) for security & privacy issues using static, dynamic, and behavioral analysis for both iOS and Android applications.

  More information can be found here:
  https://www.datatheorem.com/products/mobile-secure
author: https://github.com/datatheorem
requirements:
  - curl
  - jq
configuration:
  properties:
    UPLOAD_API_KEY:
      type: string
    SIGNED_BINARY_PATH:
      type: string
    SOURCEMAP_PATH:
      type: string
    POLL_SCAN_RESULTS:
      type: "boolean"
      default: false
      description: |
        If the plugin should wait until the scan is completed and check the scan results
        When set to `true`, `MOBILE_RESULTS_API_KEY` also needs to be set
    MOBILE_RESULTS_API_KEY:
      type: string
  required:
    - UPLOAD_API_KEY
    - SIGNED_BINARY_PATH
  additionalProperties: false
